# -*- coding: utf-8 -*-
"""AI FIRST LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjEyrud_Z9ksRdn-gEKm4fuQUdpF4sOY

# **Division**
"""

a=10;
b=7;
print(" Division of a and b =",a / b);

"""# **MULTIPLICATION**

"""

a=10;
b=7;
print(" Multiplication of a and b =",a * b);

"""# **SUBTRACTION**

"""

a=10;
b=7;
print(" Subtraction of a and b =",a - b);

"""# HELLO

"""

print("hello");

"""# **ADDITION**

"""

a=10;
b=7;
print(" Addition of a and b =",a + b);