# -*- coding: utf-8 -*-
"""AI FIRST LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjEyrud_Z9ksRdn-gEKm4fuQUdpF4sOY
"""

a=10;
b=7;
print(" Addition of a and b =",a + b);
print(" Subtraction of a and b =",a - b);
print(" Multiplication of a and b =",a * b);
print(" Division of a and b =",a / b);

"""# **Division**
# New Section

# **MULTIPLICATION**
# New Section

# **SUBTRACTION**
# New Section

# HELLO
# New Section

# **ADDITION**
# New Section
"""