# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qU9xOLAd6sbR7db_gZJL-AudQzITmru

# **Lists**
1.Create a list of 10 integers. \
2.Find and print the sum ,maximum and minimum value.\
3.Add a new element in list and remove an existing one.\
4.Print new list.\
5.Sort the list in ascending and decending order.
"""

# create a list of 10 integers
a= [1,2,3,4,5,6,7,8,9,10]
print('List:',a)
#sum,max,min
print('Sum:',sum(a))
print('Max:',max(a))
print('Min:',min(a))
#Add and remove element
a.append(11) #to add new item use append
print('Add:',a)
a.remove(5)
print('Remove:',a)
#print updated list
print('Updated List:',a)
#Sort ascending and decending order
a.sort()
print('Ascending:',a)
a.sort(reverse=True)
print('Decending:',a)
# while(true) will run an infinity loop forever

"""# **Tuples**
1.Create a tuple with 5 Strings.\
2.Access and print the second and last element.\
3.Try to modify and an element and not the error.\
4.Convert the tuple into a list and modify it.
"""

#create a tuple with 5 strings
a=('apple','orange','cherry','kiwi','berry')
print('Tuple:',a)
#tuple dont allow add or remove so first need to convert it to a list \
#Access and print the second and last element

print('Second Element:',a[1])
print('Last Element:',a[-1])
#add element
#a.append('banana')
# AttributeError                            Traceback (most recent call last)
# /tmp/ipython-input-2312869946.py in <cell line: 0>()
#       8 print('Last Element:',a[-1])
#       9 #add element
# ---> 10 a.append('banana')
#      11

# AttributeError: 'tuple' object has no attribute 'append'

#Convert the tuple into a list and modify it
a=list(a)
a.append('banana')
print('Updated List:',a)
b=tuple(a)
print('Updated Tuple:',b)

"""# **Sets**
1.Create two sets with some common and unique elements.\
2.Perform Union,intersection and difference operations.
"""

#Create two sets with some common and unique elements
a={1,2,3,4,5}
b={4,5,6,7,8}
print('Set A:',a)
print('Set B:',b)
#Perform Union,intersection and difference operations
print('Union:',a.union(b))
print('Intersection:',a.intersection(b))
print('Difference:',a.difference(b))

"""# **Dictionaries**
1.Create 5 -key values pairs and marks.\
2.Print keys and values.\
3.Update value.
"""

#Create 5 -key values pairs and marks
students={ 'Ali': 85,
           'Sara': 92,
           'Ahmed': 78,
           'Fatima': 95,
           'Omar': 88
           }

print(students)

# Print keys and values
print('Keys:', students.keys())
print('Values:', students.values())

# Update value
students['Ali'] = 90
print('Updated Dictionary:', students)

"""# **Numpy**

# **Matplotlib**
"""