# -*- coding: utf-8 -*-
"""RepResultFuzzy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAiXlkXtmDKKNWSyelcIkwuioy3Fi-EE
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# -----------------------------
# RESTAURANT TIPPING SYSTEM
# -----------------------------
def restaurant_tipping():
    service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
    food = ctrl.Antecedent(np.arange(0, 11, 1), 'food')
    tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')

    # UPDATED MEMBERSHIP FUNCTIONS
    service['poor'] = fuzz.trimf(service.universe, [0, 0, 4])
    service['average'] = fuzz.trimf(service.universe, [2, 5, 8])
    service['good'] = fuzz.trimf(service.universe, [6, 10, 10])

    food['poor'] = fuzz.trimf(food.universe, [0, 0, 4])
    food['average'] = fuzz.trimf(food.universe, [3, 5, 8])
    food['good'] = fuzz.trimf(food.universe, [7, 10, 10])

    tip['low'] = fuzz.trimf(tip.universe, [0, 0, 10])
    tip['medium'] = fuzz.trimf(tip.universe, [5, 13, 20])
    tip['high'] = fuzz.trimf(tip.universe, [15, 25, 25])

    # Rules stay same
    rule1 = ctrl.Rule(service['poor'] | food['poor'], tip['low'])
    rule2 = ctrl.Rule(service['average'], tip['medium'])
    rule3 = ctrl.Rule(service['good'] | food['good'], tip['high'])

    tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    tipping = ctrl.ControlSystemSimulation(tipping_ctrl)

    tipping.input['service'] = 4.2     # UPDATED INPUT
    tipping.input['food'] = 7.5        # UPDATED INPUT

    tipping.compute()

    print("UPDATED TIP OUTPUT:", tipping.output['tip'])
    tip.view(sim=tipping)

# -----------------------------
# ABS BRAKING SYSTEM (UPDATED)
# -----------------------------
def abs_brake_system():
    speed = ctrl.Antecedent(np.arange(0, 121, 1), 'speed')
    slip = ctrl.Antecedent(np.arange(0, 11, 1), 'slip')
    brake = ctrl.Consequent(np.arange(0, 101, 1), 'brake')

    # Updated membership functions
    speed['low'] = fuzz.trimf(speed.universe, [0, 0, 50])
    speed['medium'] = fuzz.trimf(speed.universe, [30, 60, 90])
    speed['high'] = fuzz.trimf(speed.universe, [70, 120, 120])

    slip['low'] = fuzz.trimf(slip.universe, [0, 0, 3])
    slip['medium'] = fuzz.trimf(slip.universe, [2, 5, 8])
    slip['high'] = fuzz.trimf(slip.universe, [6, 10, 10])

    brake['low'] = fuzz.trimf(brake.universe, [0, 0, 40])
    brake['medium'] = fuzz.trimf(brake.universe, [30, 50, 80])
    brake['high'] = fuzz.trimf(brake.universe, [70, 100, 100])

    # Rules (same logic)
    rule1 = ctrl.Rule(speed['low'] | slip['low'], brake['high'])
    rule2 = ctrl.Rule(speed['medium'], brake['medium'])
    rule3 = ctrl.Rule(speed['high'] | slip['high'], brake['low'])

    braking_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    braking = ctrl.ControlSystemSimulation(braking_ctrl)

    braking.input['speed'] = 82      # UPDATED INPUT
    braking.input['slip'] = 6        # UPDATED INPUT

    braking.compute()

    print("UPDATED BRAKE OUTPUT:", braking.output['brake'])
    brake.view(sim=braking)

# Run both
restaurant_tipping()
abs_brake_system()

plt.show()

"""## **Fuzzy Inference Systems Summary**

### **1. Restaurant Tipping System**

This fuzzy system calculates the tip percentage based on two inputs:

* **Service Quality (0–10)**
* **Food Quality (0–10)**

Both inputs use updated membership functions (poor, average, good).
The output variable is **Tip (0–25%)** with low, medium, and high fuzzy sets.

**Rules:**

1. If service is poor OR food is poor → tip low
2. If service is average → tip medium
3. If service is good OR food is good → tip high

With inputs *service = 4.2* and *food = 7.5*, both medium and high rules activate.
Defuzzification gives a **tip value in the mid-to-high range**.

---

### **2. ABS Braking System**

This system adjusts brake pressure based on:

* **Speed of Car (0–120 km/h)**
* **Wheel Slip (0–10%)**

Updated membership sets classify inputs into low, medium, and high.
Output variable is **Brake Pressure (0–100%)** (low, medium, high).

**Rules:**

1. If speed low OR slip low → brake high
2. If speed medium → brake medium
3. If speed high OR slip high → brake low

Given *speed = 82* and *slip = 6*, the “high slip” condition dominates.
Defuzzification produces a **reduced brake pressure**, matching ABS behavior.

---

### **Overall**

Both systems use:

* Fuzzy membership functions
* Rule-based reasoning
* Defuzzification to convert fuzzy output into crisp values
* Visual plots to show how the final decision is made

These fuzzy systems demonstrate how real-world decisions can be made even when inputs are uncertain or imprecise.


"""