# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALj5j37K5tyy-iJM6aJWDwHcMLc10IP_

# **Numpy**
1.Import NumPy and create a 1D array of numbers from 1 to 20.\
2.Reshape it into a 4x5 matrix.\
3.Find the mean, median, and standard deviation.\
4.Perform element-wise addition and multiplication with another array (from 50 to 69).
"""

#!pip install numpy
import numpy as np

# Create 1D array
arr = np.arange(1, 21)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(50, 70) # Changed values here
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

"""# **Matplotlib**
1.Use Matplotlib to create the following plots:\
.A line plot showing example data.\
.A bar chart showing fruit quantity.\
.A pie chart showing sales distribution by region.\
2.Label the axes and add titles to the plots.
"""

import matplotlib.pyplot as plt

# Line Plot
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
plt.plot(x, y)
plt.title('Example Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

# Bar Chart
items = ['Apple', 'Banana', 'Orange', 'Grape', 'Mango']
quantity = [15, 10, 20, 12, 18]
plt.bar(items, quantity)
plt.title('Fruit Quantity')
plt.xlabel('Fruit')
plt.ylabel('Quantity')
plt.show()

# Pie Chart
regions = ['North', 'South', 'East', 'West']
sales = [40, 25, 20, 15]
plt.pie(sales, labels=regions, autopct='%1.1f%%')
plt.title('Sales Distribution by Region')
plt.show()